





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Sitecore.Mapper.Configuration.Attributes;
using Glass.Sitecore.Mapper.Configuration;
using Glass.Sitecore.Mapper.FieldTypes;
using Sitecore.Globalization;









namespace SUGNL.TDS.Website
{
 	/// <summary>
	/// IHomepage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/PageTemplates/Homepage</para>	
	/// <para>ID: 4eeeca4e-1b09-4047-abf4-78cbea602451</para>	
	/// </summary>
	public interface IHomepage : IGlassBase , global::SUGNL.TDS.Website.IMetaBase, global::SUGNL.TDS.Website.IPageBase, global::SUGNL.TDS.Website.ITitleBase
	{
	}

	
	/// <summary>
	/// Homepage
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/PageTemplates/Homepage</para>	
	/// <para>ID: 4eeeca4e-1b09-4047-abf4-78cbea602451</para>	
	/// </summary>
	[SitecoreClass(TemplateId="4eeeca4e-1b09-4047-abf4-78cbea602451")]
	public partial class Homepage  : GlassBase, IHomepage 
	{
		/// <summary>
		/// The MetaDescription field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 411f83b0-ffcf-4c64-bb8d-5c4b251493a3</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("MetaDescription")]
		public virtual string MetaDescription  {get; set;}
			
		/// <summary>
		/// The MetaKeywords field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: f29a2f77-3034-4307-84ba-0c48cdc8188d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("MetaKeywords")]
		public virtual string MetaKeywords  {get; set;}
			
		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: fc20530b-c1f3-421c-b724-321a36152e91</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Title")]
		public virtual string Title  {get; set;}
			
	
	}
}
namespace SUGNL.TDS.Website
{
 	/// <summary>
	/// ISnippet Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/DataTemplates/Snippet</para>	
	/// <para>ID: 4f88101b-127b-4963-9964-ccf09a575ec3</para>	
	/// </summary>
	public interface ISnippet : IGlassBase 
	{
	}

	
	/// <summary>
	/// Snippet
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/DataTemplates/Snippet</para>	
	/// <para>ID: 4f88101b-127b-4963-9964-ccf09a575ec3</para>	
	/// </summary>
	[SitecoreClass(TemplateId="4f88101b-127b-4963-9964-ccf09a575ec3")]
	public partial class Snippet  : GlassBase, ISnippet 
	{
	
	}
}



namespace SUGNL.TDS.Website
{
 	/// <summary>
	/// IBanner Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/DataTemplates/Banner</para>	
	/// <para>ID: 853cc71a-df49-4253-8b20-c072bf40e236</para>	
	/// </summary>
	public interface IBanner : IGlassBase 
	{
		/// <summary>
		/// The Image field.
		/// <para></para>
		/// <para>Field Type: Image</para>		
		/// <para>Field ID: 0e02d479-8216-4a17-8528-63b8d93fb545</para>
		/// <para>Custom Data: </para>
		/// </summary>
		Image Image  {get; set;}
			
		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 45e27472-168a-4bdc-95f4-cd64b0983674</para>
		/// <para>Custom Data: </para>
		/// </summary>
		string Title  {get; set;}
			
	}

	
	/// <summary>
	/// Banner
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/DataTemplates/Banner</para>	
	/// <para>ID: 853cc71a-df49-4253-8b20-c072bf40e236</para>	
	/// </summary>
	[SitecoreClass(TemplateId="853cc71a-df49-4253-8b20-c072bf40e236")]
	public partial class Banner  : GlassBase, IBanner 
	{
		/// <summary>
		/// The Image field.
		/// <para></para>
		/// <para>Field Type: Image</para>		
		/// <para>Field ID: 0e02d479-8216-4a17-8528-63b8d93fb545</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Image")]
		public virtual Image Image  {get; set;}
			
		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 45e27472-168a-4bdc-95f4-cd64b0983674</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Title")]
		public virtual string Title  {get; set;}
			
	
	}
}
namespace SUGNL.TDS.Website
{
 	/// <summary>
	/// INewsOverviewPage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/PageTemplates/NewsOverviewPage</para>	
	/// <para>ID: 893eeb21-51fa-47c9-b8a7-185ea0445322</para>	
	/// </summary>
	public interface INewsOverviewPage : IGlassBase , global::SUGNL.TDS.Website.IPageBase, global::SUGNL.TDS.Website.IMetaBase, global::SUGNL.TDS.Website.ITitleBase
	{
	}

	
	/// <summary>
	/// NewsOverviewPage
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/PageTemplates/NewsOverviewPage</para>	
	/// <para>ID: 893eeb21-51fa-47c9-b8a7-185ea0445322</para>	
	/// </summary>
	[SitecoreClass(TemplateId="893eeb21-51fa-47c9-b8a7-185ea0445322")]
	public partial class NewsOverviewPage  : GlassBase, INewsOverviewPage 
	{
		/// <summary>
		/// The MetaDescription field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 411f83b0-ffcf-4c64-bb8d-5c4b251493a3</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("MetaDescription")]
		public virtual string MetaDescription  {get; set;}
			
		/// <summary>
		/// The MetaKeywords field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: f29a2f77-3034-4307-84ba-0c48cdc8188d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("MetaKeywords")]
		public virtual string MetaKeywords  {get; set;}
			
		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: fc20530b-c1f3-421c-b724-321a36152e91</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Title")]
		public virtual string Title  {get; set;}
			
	
	}
}





namespace SUGNL.TDS.Website
{
 	/// <summary>
	/// IContentPage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/PageTemplates/ContentPage</para>	
	/// <para>ID: ba577308-fa5c-43ad-86d1-effbf5371d4f</para>	
	/// </summary>
	public interface IContentPage : IGlassBase , global::SUGNL.TDS.Website.IMetaBase, global::SUGNL.TDS.Website.ITitleBase, global::SUGNL.TDS.Website.IIntroBase, global::SUGNL.TDS.Website.IPageBase, global::SUGNL.TDS.Website.IContentTextBase
	{
	}

	
	/// <summary>
	/// ContentPage
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/PageTemplates/ContentPage</para>	
	/// <para>ID: ba577308-fa5c-43ad-86d1-effbf5371d4f</para>	
	/// </summary>
	[SitecoreClass(TemplateId="ba577308-fa5c-43ad-86d1-effbf5371d4f")]
	public partial class ContentPage  : GlassBase, IContentPage 
	{
		/// <summary>
		/// The MetaDescription field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 411f83b0-ffcf-4c64-bb8d-5c4b251493a3</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("MetaDescription")]
		public virtual string MetaDescription  {get; set;}
			
		/// <summary>
		/// The MetaKeywords field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: f29a2f77-3034-4307-84ba-0c48cdc8188d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("MetaKeywords")]
		public virtual string MetaKeywords  {get; set;}
			
		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: fc20530b-c1f3-421c-b724-321a36152e91</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Title")]
		public virtual string Title  {get; set;}
			
		/// <summary>
		/// The Intro field.
		/// <para></para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 5e82bcb3-e174-4f0d-9248-24be233a4635</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Intro")]
		public virtual string Intro  {get; set;}
			
		/// <summary>
		/// The Content field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: 3089399a-4f48-4bfe-b0b6-34f63c28797f</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Content")]
		public virtual string Content  {get; set;}
			
	
	}
}

namespace SUGNL.TDS.Website
{
 	/// <summary>
	/// INewsDetailPage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/PageTemplates/NewsDetailPage</para>	
	/// <para>ID: d44bb872-ffd7-4caf-b2d8-e58f076641de</para>	
	/// </summary>
	public interface INewsDetailPage : IGlassBase , global::SUGNL.TDS.Website.IMetaBase, global::SUGNL.TDS.Website.IPageBase, global::SUGNL.TDS.Website.IIntroBase, global::SUGNL.TDS.Website.IContentTextBase, global::SUGNL.TDS.Website.ITitleBase
	{
		/// <summary>
		/// The Date field.
		/// <para></para>
		/// <para>Field Type: Date</para>		
		/// <para>Field ID: 0e36d427-8cc1-418b-b317-2d9f831325cc</para>
		/// <para>Custom Data: </para>
		/// </summary>
		DateTime Date  {get; set;}
			
	}

	
	/// <summary>
	/// NewsDetailPage
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/PageTemplates/NewsDetailPage</para>	
	/// <para>ID: d44bb872-ffd7-4caf-b2d8-e58f076641de</para>	
	/// </summary>
	[SitecoreClass(TemplateId="d44bb872-ffd7-4caf-b2d8-e58f076641de")]
	public partial class NewsDetailPage  : GlassBase, INewsDetailPage 
	{
		/// <summary>
		/// The Date field.
		/// <para></para>
		/// <para>Field Type: Date</para>		
		/// <para>Field ID: 0e36d427-8cc1-418b-b317-2d9f831325cc</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Date")]
		public virtual DateTime Date  {get; set;}
			
		/// <summary>
		/// The MetaDescription field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 411f83b0-ffcf-4c64-bb8d-5c4b251493a3</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("MetaDescription")]
		public virtual string MetaDescription  {get; set;}
			
		/// <summary>
		/// The MetaKeywords field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: f29a2f77-3034-4307-84ba-0c48cdc8188d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("MetaKeywords")]
		public virtual string MetaKeywords  {get; set;}
			
		/// <summary>
		/// The Intro field.
		/// <para></para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 5e82bcb3-e174-4f0d-9248-24be233a4635</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Intro")]
		public virtual string Intro  {get; set;}
			
		/// <summary>
		/// The Content field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: 3089399a-4f48-4bfe-b0b6-34f63c28797f</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Content")]
		public virtual string Content  {get; set;}
			
		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: fc20530b-c1f3-421c-b724-321a36152e91</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Title")]
		public virtual string Title  {get; set;}
			
	
	}
}

