





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Sitecore.Mapper.Configuration.Attributes;
using Glass.Sitecore.Mapper.Configuration;
using Glass.Sitecore.Mapper.FieldTypes;
using Sitecore.Globalization;


namespace SUGNL.TDS.Website
{

	public interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }
	}
}
namespace SUGNL.TDS.Website
{
 	/// <summary>
	/// ITitleBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/BaseTemplates/TitleBase</para>	
	/// <para>ID: 02b041f5-3b31-4724-818b-ac33e5412024</para>	
	/// </summary>
	public interface ITitleBase : IGlassBase 
	{
		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: fc20530b-c1f3-421c-b724-321a36152e91</para>
		/// <para>Custom Data: </para>
		/// </summary>
		string Title  {get; set;}
			
	}

	
	/// <summary>
	/// TitleBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/BaseTemplates/TitleBase</para>	
	/// <para>ID: 02b041f5-3b31-4724-818b-ac33e5412024</para>	
	/// </summary>
	[SitecoreClass(TemplateId="02b041f5-3b31-4724-818b-ac33e5412024")]
	public partial class TitleBase  : GlassBase, ITitleBase 
	{
		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: fc20530b-c1f3-421c-b724-321a36152e91</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Title")]
		public virtual string Title  {get; set;}
			
	
	}
}
namespace SUGNL.TDS.Website
{
 	/// <summary>
	/// IMetaBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/BaseTemplates/MetaBase</para>	
	/// <para>ID: 0a6cbac6-346f-4053-ab0f-dcac5463c2f9</para>	
	/// </summary>
	public interface IMetaBase : IGlassBase 
	{
		/// <summary>
		/// The MetaDescription field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 411f83b0-ffcf-4c64-bb8d-5c4b251493a3</para>
		/// <para>Custom Data: </para>
		/// </summary>
		string MetaDescription  {get; set;}
			
		/// <summary>
		/// The MetaKeywords field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: f29a2f77-3034-4307-84ba-0c48cdc8188d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		string MetaKeywords  {get; set;}
			
	}

	
	/// <summary>
	/// MetaBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/BaseTemplates/MetaBase</para>	
	/// <para>ID: 0a6cbac6-346f-4053-ab0f-dcac5463c2f9</para>	
	/// </summary>
	[SitecoreClass(TemplateId="0a6cbac6-346f-4053-ab0f-dcac5463c2f9")]
	public partial class MetaBase  : GlassBase, IMetaBase 
	{
		/// <summary>
		/// The MetaDescription field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 411f83b0-ffcf-4c64-bb8d-5c4b251493a3</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("MetaDescription")]
		public virtual string MetaDescription  {get; set;}
			
		/// <summary>
		/// The MetaKeywords field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: f29a2f77-3034-4307-84ba-0c48cdc8188d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("MetaKeywords")]
		public virtual string MetaKeywords  {get; set;}
			
	
	}
}


namespace SUGNL.TDS.Website
{
 	/// <summary>
	/// IIntroBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/BaseTemplates/IntroBase</para>	
	/// <para>ID: 29ec2750-290b-4561-ab53-34c1d3e82bae</para>	
	/// </summary>
	public interface IIntroBase : IGlassBase 
	{
		/// <summary>
		/// The Intro field.
		/// <para></para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 5e82bcb3-e174-4f0d-9248-24be233a4635</para>
		/// <para>Custom Data: </para>
		/// </summary>
		string Intro  {get; set;}
			
	}

	
	/// <summary>
	/// IntroBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/BaseTemplates/IntroBase</para>	
	/// <para>ID: 29ec2750-290b-4561-ab53-34c1d3e82bae</para>	
	/// </summary>
	[SitecoreClass(TemplateId="29ec2750-290b-4561-ab53-34c1d3e82bae")]
	public partial class IntroBase  : GlassBase, IIntroBase 
	{
		/// <summary>
		/// The Intro field.
		/// <para></para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 5e82bcb3-e174-4f0d-9248-24be233a4635</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Intro")]
		public virtual string Intro  {get; set;}
			
	
	}
}



namespace SUGNL.TDS.Website
{
 	/// <summary>
	/// IPageBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/BaseTemplates/PageBase</para>	
	/// <para>ID: 4cf43de9-a89b-4139-9ed2-14b267e0ddd6</para>	
	/// </summary>
	public interface IPageBase : IGlassBase 
	{
	}

	
	/// <summary>
	/// PageBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/BaseTemplates/PageBase</para>	
	/// <para>ID: 4cf43de9-a89b-4139-9ed2-14b267e0ddd6</para>	
	/// </summary>
	[SitecoreClass(TemplateId="4cf43de9-a89b-4139-9ed2-14b267e0ddd6")]
	public partial class PageBase  : GlassBase, IPageBase 
	{
	
	}
}






namespace SUGNL.TDS.Website
{
 	/// <summary>
	/// IContentTextBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/BaseTemplates/ContentTextBase</para>	
	/// <para>ID: efca2812-d85a-414d-80c4-8998f543b44e</para>	
	/// </summary>
	public interface IContentTextBase : IGlassBase 
	{
		/// <summary>
		/// The Content field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: 3089399a-4f48-4bfe-b0b6-34f63c28797f</para>
		/// <para>Custom Data: </para>
		/// </summary>
		string Content  {get; set;}
			
	}

	
	/// <summary>
	/// ContentTextBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/SUGNL TDS V5 Demo/BaseTemplates/ContentTextBase</para>	
	/// <para>ID: efca2812-d85a-414d-80c4-8998f543b44e</para>	
	/// </summary>
	[SitecoreClass(TemplateId="efca2812-d85a-414d-80c4-8998f543b44e")]
	public partial class ContentTextBase  : GlassBase, IContentTextBase 
	{
		/// <summary>
		/// The Content field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: 3089399a-4f48-4bfe-b0b6-34f63c28797f</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField("Content")]
		public virtual string Content  {get; set;}
			
	
	}
}


